### ISSUE TITLE
availMemory error in HPC

### ISSUE THREAD

**Issue by ufuomababatunde** [phac-nml/monkeypox-nf#7]
Tried running it in HPC and got this error below but it ran fine with done in local desktop.
```
Local avail `memory` attribute cannot zero. Expression: (availMemory > 0). Values: availMemory = 0

 -- Check script '/data/apps/monkeypox-nf/./workflows/mpx_main.nf' at line: 30 or see '.nextflow.log' file for more details
```

**Comment by DarianHole** [comment]
Hi @ufuomababatunde,

Thanks for the issue report! What executor are you using for your HPC environment? It likely has to do with that not being set correctly and you may need to generate your own config file or I can look to add one in for you.

**Comment by ufuomababatunde** [comment]
Hello @DarianHole ,

Thank you for the idea. I added the lines below in the _nextflow.config_ and it worked.

````
executor {
  name = 'local'
  cpus = 35
  memory = '150 GB'
}
````
